apiVersion: k8s.nginx.org/v1
kind: VirtualServer

metadata:
  name: cafe
  namespace: nginx-cafe

spec:
  host: cafe.example.com

  tls:
    secret: cafe-secret

  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
    use-cluster-ip: true

  - name: hot-chocolate
    service: hot-chocolate-svc
    port: 80
    use-cluster-ip: true

  - name: tea
    service: tea-svc
    port: 80
    use-cluster-ip: true

  routes:
  - path: /coffee
    action:
      proxy:
        upstream: coffee
        requestHeaders:
          set:
          - name: Host
            value: coffee-svc.cafe-ingress.svc.cluster.local

  - path: /hot-chocolate
    action:
      proxy:
        upstream: hot-chocolate
        requestHeaders:
          set:
          - name: Host
            value: hot-chocolate-svc.cafe-ingress.svc.cluster.local

  - path: /tea
    action:
      proxy:
        upstream: tea
        requestHeaders:
          set:
          - name: Host
            value: tea-svc.cafe-ingress.svc.cluster.local
