name: Bash-Unit-Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  bash-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        run: |
          git_workflow=$GITHUB_WORKFLOW
          echo "Git Workflow:      ${git_workflow}"
          \
          git_branch=${GITHUB_REF#refs/heads/}
          echo "Git Branch:        ${git_branch}"
          \
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "Git Hash:          ${git_hash}"
          \
          raw_tag="${git_workflow}/${git_branch}:${git_hash}"
          echo "Raw Tag:           ${raw_tag}"
          \
          lowercase_tag=$(echo "${raw_tag}" | tr '[:upper:]' '[:lower:]')
          echo "Lowercase Tag:     ${lowercase_tag}"
          \
          git_runner_code_loc="/home/runner/work/DevSecOps/DevSecOps"
          echo "Volumn Loc:        ${git_runner_code_loc}"
          \
          dockerfile="${git_runner_code_loc}/bash/docker/bats.Dockerfile"
          echo "Dockerfile:        ${dockerfile}"
          \
          mount_loc="/root/git/DevSecOps"
          echo "Mount Loc:         ${mount_loc}"
          \
          echo "Who am I?"
          whoami
          \
          echo "Current Directory:"
          pwd
          \
          echo "List ${git_runner_code_loc}"
          ls -al ${git_runner_code_loc}
          \
          docker build --tag ${lowercase_tag} -f ${dockerfile} .
          docker run -i -t "${lowercase_tag}"
